USE [master]
GO

CREATE DATABASE [Csvm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Csvm', FILENAME = N'/var/opt/mssql/data/Csvm.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Csvm_log', FILENAME = N'/var/opt/mssql/data/Csvm_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Csvm] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Csvm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Csvm] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Csvm] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Csvm] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Csvm] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Csvm] SET ARITHABORT OFF 
GO
ALTER DATABASE [Csvm] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Csvm] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Csvm] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Csvm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Csvm] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Csvm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Csvm] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Csvm] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Csvm] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Csvm] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Csvm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Csvm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Csvm] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Csvm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Csvm] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Csvm] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Csvm] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Csvm] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Csvm] SET  MULTI_USER 
GO
ALTER DATABASE [Csvm] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Csvm] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Csvm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Csvm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Csvm] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Csvm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Csvm', N'ON'
GO
ALTER DATABASE [Csvm] SET QUERY_STORE = OFF
GO
USE [Csvm]
GO


CREATE USER [csvmDbAdmin] FOR LOGIN [csvmDbAdmin] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [csvmDbAdmin]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [csvmDbAdmin]
GO